type = "service_account"
project_id = "face-detection-2024"
private_key_id = "6ac339cd941e64f936a264580a6a60a855b57f74"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDV6kus/q7TyHrf
e4KwMpuuI9SJFHfxOFamIE2Lz5QYw80NCD0OPJfSi9Hv9tF2B0DHCyFBb1i//drL
+OCD2sPJsD/hgDMijCa/vV1WkzYHsoO/3kBxLKRC633OzsvSBbuxUkVMBgnyn06T
H1MPuJwx5FrbpXoc1CwFRfr2Xhp/LaEEruM6TwPb2eIlvZWrShLC4MOfjiI10SNg
qGZdxoGnXDu1N5VoHMVWjzYriufePsit5utgBbmaEJxbo0PrGfexmftTEFuiUCMO
0Jl765dVcIS7rkFDsO+vPM4qVc75R1TkWdwBFwyqSUeaoQPIX5aGa5glmTPbQt69
S2Ulp0UxAgMBAAECggEAPe9jT8hBmCIAqXoaQae1eXr4S2Q4wge81sadjTBhwbXX
RcGv49JZZuWCuEavKMw6ziaDz21MtfHrComZf7O0Yk38gO7cX1FS2ssaHjnrN9lQ
2hmgcOQq/xEt0NYBH2L3kASw+az57lx/pIs6QmACIVPrlpLXw0cPI8u6OODQLSfi
ZxkTkooOsL2V/wtie5hvliMCHo0JHvdkBXjc0gfJIaRD/tyDvW9j+1/yFb4ie4GY
ikwtRUTscgW11zBk2A5ArAbvZnTgyIVvPnz8x15LL4Pm02sHrrveYHd1GLb5BR3K
AraRqfqrMoqxJhXjAJ+BjHmIJKw5srAPsoNyfTXWXQKBgQDq0RfOhYPs1L4FCIjF
hyTmSmlQ257vnXn6vBfJDCgZ1akXkRaJxpx4fxZz378sDaZhjC847bsGXjyAgp8K
d1KcERZcP2Sb03HMrkVo7VLOSCVKAubmEJ/teOh6oZGl+A96tlTMDHPs67UJJtf/
pMyciOnPFqXGJbVSfuft/y7lpwKBgQDpNn9yxhE+CMO6TDSQJs3azJdWrqEZosoX
rCYOIrpUpFz57LnzAnnRktd9WHYZuFYvru+tyTABIkz3h7bFB1HdW1zCoo4Qmlfp
csR79LLzhopMGC26WCIrEsE1RUf5nyNUf/V89YJ464VCV0AXJDp09wet9v+llBIH
TgliEVoJZwKBgG5E8qERIfq9jN5gO5pG9JUQrJREDkcH9JhCbAkFpG89XsKqZ6Mb
ma8cPzb7A5N0dYWphyN8wC8lYdQXgwgvMKQJgi6ftmdWzEIKNJ4plJE6YAh5hGTV
ucSS2tl7tiHyc5J0vS11S5setU0u6JAsm8mGogWV5RM/8f5jihbBlwxRAoGBAL6G
dGaq5Ak/FdBMU6D04rZ+8KCzeA++i8X9MPXZb0qZIRBZUqzyd908TuorbAilLVw1
WcArnhk/EYwkBrA+w6XI7yZfsRplTa79wQHXrp7/alqyYiFbwUZZQxknKZ8IYM+2
3jKhTF9HYo4JQ+XkBhHqgw6fvMlkB7qKCWZh8KG/AoGBALycBl2BBrtqblsuByC2
VJ2srBC2vn6o9a3ZVtoPsg+n6Tm6R4mj56bAwlq1OJE+XXmuuFqLE2xeBE1EvUnm
E5NWJV8BXtqkOb4djMl9eckI3QJ4KhKcLL3D8xys60iyGyZHw+QEoAkczaIycNFo
Md1QFW0z8BLiC+11gQhLqUDn
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-pevrv@face-detection-2024.iam.gserviceaccount.com"
client_id = "114058815837971717035"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-pevrv%40face-detection-2024.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
