type = "service_account"
project_id = "face-detection-2024"
private_key_id = "8c934890d2a9904040816d46c1ccd5f98fe4ce3e"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDqgkPfioSTlEUJ
T1xk8mk9Fnhhdch1eU7+dCUS6mY34gpOpzQIUhWdTT+nGlfwNlG7B2ZtnsE2fjLl
cFCSPrG0+ipTtuAcA6gfnXinMwCyT2PpW60sp2iyydTC0ddaJSTHLipYB/Cw3X6d
B+F3Xt9FUv6eNkIrmf1eUYT9VxvgSB+djmcD+139/HBhdFTF1caagV2cTTT/16yb
aLqvgCgksvw/DtarFJwBRF9vIet2roCv7PCAY63pQ6qvuJIInYod8ncpvyeQxooe
g/h5I27wpluPeHWap51GiAjDeMPLTV4S+VIeQMPQfKgUBPFxPa6N4Ir73eEESSYd
Hbo06YxnAgMBAAECggEAUoz0k5ZRQRoqizJyld53iVeFnNk3bZL8abo86sG0pete
MX3OZTdwAGWXCJ3PYvHcJ3hdaC1AWoxmIjo9Qp3rNIfzqnBvx6zJ3Ac017aughZM
V3M8LMHpqzY9PS9dHZCBt9PaeA6jfb8auPBzP/AXrHGgy9TRykN022Ta6ctmNrbA
NZwPFHV+6NNklhJ4RlF5b3b+VlTOt8HJozkfHSCO2vvWEDrdQ8LrX65yO1IbMQAo
zpX3McYOvDg7aJBtYpSYKh+h9sjJaItpJq1voTmCRtHjDSKPAfZpD0Gh3Sk3bsWW
o3m21qoPNki6L5mwyIjRkMhC+FsjNR1zNsHc7RbqsQKBgQD/GcElXxLCfawb053U
HnsWgybPpKnVHe+Reop7X58THzEDJmy24jfTjal6XJHy94+LzvejOjlt7n0MtTPA
QC625MYoBoRXgm+Fv6Wi2pw1CbNnzJ9d3qCFeOjXKXl6V6LEdgWgYpJOjobuhITJ
7tZdGuD6+QEIm9PE5SFh83UUZQKBgQDrVezaIPaB6KQpN2fGtZU8kIZHETEzT951
Zk15/QkCEtDnL3tssyIUhgy5r+jIXoECQMfJKP02ydnc40jDz+mLwLtu0zbnkPBD
7miNErKY89dvE/27eJax1B3nu73EAOS1boUDPrkcuYQW/aW+3Yimw8iuYxHNr5Sw
3kSy0OoS2wKBgQDfnUvZ3oUrR85edhmbnzx2d3DGA6l7z0n5VFmf3CotMOJdyIjz
p0kYgM1XHV4yhR+nhj09MAS3gJ7NTOmYVKqeV9v7qfrIWuY3b89Z+heDxoUlMBFi
z4wWc+5m7Uw3Girr3CkCdmWZxwYwfqmH+XyfELi2Rx/I1A/GQLQKkMbIoQKBgHK5
n86y1Rl9nVHOhdPUP92Xoy5QDkkyfYOEDO8UUOjm3Vpmxme2aD3TH68CN5w+nevI
Qt0pE1A7VO8fCiETYYpUucsMQq7e9JJZTjS/0btI3FR1TXOwFN66Rp3q41cDDHv6
VfPAByQeuGsw2jVS8EREG7gP6eT43KbgpGL7/7CTAoGBAM4RBR15QuQALpQIGbSG
hAGxSpxi6+0yMXYt8IBqrwhuc36BtvY1v0NoMwtvXl6wsUcg9HVa9qT+LqLzx1v+
5S/S1YiedlK4eMPfhcPqfwcHH1GC9Gjqzvm6fqYW2k8MxLBPhfibpi4S9Ez/6REY
WemFdyHQnrf5wJc36VX6gmaY
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-pevrv@face-detection-2024.iam.gserviceaccount.com"
client_id = "114058815837971717035"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-pevrv%40face-detection-2024.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
